---
title: "D1 data 2021"
output: html_document
---

```{r libs, include=FALSE}

library(tidyverse)
library(ggplot2)
detach("package:dplyr")
library(dplyr)

```

Below you'll find the the full 2021 data for tank D1 including the actual temperature `temp`, the `setpoint` and the `state` visualized statically and as an interactive. Here's a peek into the data:


```{r}

df <- read_csv('../../data/v2/output/D1-2021.csv', col_types = cols(.default = "?", state = "i"))
df

```

And here are the visuals. Note that the interaactive chart doesn't support a secondary axes, so 
- the state value 1 is mapped to 0℉, 
- 2 is mapped to 50℉ and 
- 3 to 100℉

```{r}

linear_scale <- function(x) {
  ((3-1)*(x-0)/(100-0)) + 1
}

invert_scale <- function(x) {
  ((100-0)*(x-1)/(3-1)) + 0
}

(p <- ggplot(df, aes(x = time)) +
  geom_line(aes(y = invert_scale(state), colour = "state"), size = 0.5) +
  geom_line(aes(y = sp, colour = "setpoint")) +
  geom_line(aes(y = temp, colour = "temp")) +
  scale_colour_manual("", breaks = c("temp", "setpoint", "state"), values = c("orange", "lightskyblue", "grey")) +
  scale_y_continuous(
    name = "Temperatures",
    sec.axis = sec_axis(trans = ~linear_scale(.), name = "State")
  ))

plotly::ggplotly(p, width = 1000)


```

